=== sia4/dp2_labs/lab1/dtd/nffgInfo.dtd
<!-- DTD for Network Function-Forwarding Graph -->
<!ELEMENT serviceProvider (nffg)*>
<!ELEMENT nffg (node|link|policy)*>
<!ATTLIST nffg 
			name		ID		#REQUIRED
			update_time CDATA 	#IMPLIED>
<!ELEMENT node EMPTY>
<!ATTLIST node 
			name 	CDATA		#REQUIRED
			node_type	(FW|DPI|NAT|SPAM|CACHE|VPN|WEB_SERVER|WEB_CLIENT
			|MAIL_SERVER|MAIL_CLIENT)	#REQUIRED>
<!ELEMENT link EMPTY>
<!ATTLIST link 
			name	CDATA	#REQUIRED
			source	CDATA 	#REQUIRED
			dest	CDATA 	#REQUIRED>
<!ELEMENT policy (traversed_func|result)*>
<!ATTLIST policy
			name 	ID							#REQUIRED
			source	CDATA 						#REQUIRED
			dest	CDATA 						#REQUIRED
			value	(true|false)				#REQUIRED
			type	(reachability|traversal) 	#REQUIRED>		
<!ELEMENT traversed_func EMPTY>
<!ATTLIST traversed_func
			type (FW|DPI|NAT|SPAM|CACHE|VPN|WEB_SERVER|WEB_CLIENT
			|MAIL_SERVER|MAIL_CLIENT)   		#REQUIRED>
<!ELEMENT result (message)>
<!ATTLIST result
			value	(true|false)				#REQUIRED
			v_time	CDATA						#REQUIRED>
<!ELEMENT message (#PCDATA)>

=== sia4/dp2_labs/lab1/dtd/nffgInfo.xml
<?xml version="1.0"?>
<!DOCTYPE serviceProvider SYSTEM "nffgInfo.dtd">
<serviceProvider>
	<nffg name="nffg1" update_time="2016-09-25T17:45:20.000+02:00">
		<node name="webClient1" node_type="WEB_CLIENT"/>
		<node name="NAT1" node_type="NAT"/>
		<node name="firewall1" node_type="FW"/>
		<node name="webServer1" node_type="WEB_SERVER"/>
		<link name="link1" source="webClient1" dest="NAT1"/>
		<link name="link2" source="NAT1" dest="firewall1"/>
		<link name="link3" source="firewall1" dest="webServer1"/>
		<policy name="policy1" source="webClient1" dest="webServer1" 
			value="true" type="reachability">
			<result value="true" v_time="2016-09-25T17:46:20.000+02:00">
				<message>The policy is satisfied</message>
			</result>
	</policy>
	</nffg>
	<nffg name="nffg2" update_time="2016-09-25T17:45:20.000+02:00">
		<node name="webClient3" node_type="WEB_CLIENT"/>
		<node name="NAT3" node_type="NAT"/>
		<node name="firewall3" node_type="FW"/>
		<node name="webServer3" node_type="WEB_SERVER"/>
		<link name="link5" source="webClient3" dest="NAT3"/>
		<link name="link6" source="NAT3" dest="firewall3"/>
		<link name="link4" source="firewall3" dest="webServer3"/>
		<policy name="policy2" source="webClient3" dest="webServer3" 
			value="true" type="traversal">
			<traversed_func type="FW"/>
			<result value="true" v_time="2016-09-25T17:46:20.000+02:00">
				<message>The policy is satisfied</message>
			</result>
		</policy>
	</nffg>
</serviceProvider>
